name: build-and-test

inputs:
  package: 
    required: true

runs:
  defaults:
      run:
        working-directory: ./packages/${{ inputs.package }}/
  strategy:
    matrix:
      node-version: [18.x]
  steps:
  - name: Use Node.js ${{ matrix.node-version }}
    uses: actions/setup-node@v3
    with:
      node-version: ${{ matrix.node-version }}
      cache: 'yarn'
      cache-dependency-path: ./packages/${{ inputs.package }}/yarn.lock
  - run: yarn install
  - run: yarn build