# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: Checkout
    - uses: './.github/templates/build-and-test'
      name: Build and Test API
      with:
        package: 'api'
  bot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: Checkout
    - uses: './.github/templates/build-and-test'
      name: Build and Test Bot
      with:
        package: 'bot'
  scrape:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: Checkout
    - uses: './.github/templates/build-and-test'
      name: Build and Test Scrape
      with:
        package: 'scrape'
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: Checkout
    - uses: './.github/templates/build-and-test'
      name: Build and Test Sync
      with:
        package: 'sync'