name: Hearthbot CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  #######
  # API #
  #######

  api-setup:
    runs-on: ubuntu-latest
    defaults:
       run:
         working-directory: ./packages/api/
    outputs:
      has_files_changed: ${{ steps.validate-files.outputs.has_files_changed }}
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Get changed files
      id: changed-files-root
      uses: tj-actions/changed-files@v29.0.1
      with:
        since_last_remote_commit: "true"

    - name: Validate changed files
      id: validate-files
      run: |
        for file in ${{ steps.changed-files-root.outputs.all_changed_and_modified_files }}; do
          if [[ $file == packages/api/* ]] || [[ $file == .github/* ]]; then
            echo "Detected change in $file"
            echo ::set-output name=has_files_changed::1
            break
          fi
        done

  api-build:
    needs: api-setup
    if: needs.api-setup.outputs.has_files_changed == 1
    runs-on: ubuntu-latest
    defaults:
       run:
         working-directory: ./packages/api/
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'yarn'
        cache-dependency-path: ./packages/api/yarn.lock
    - run: yarn install
    - run: yarn build
    - run: yarn test

  #######
  # Bot #
  #######

  bot-setup:
    runs-on: ubuntu-latest
    defaults:
       run:
         working-directory: ./packages/bot/
    outputs:
      has_files_changed: ${{ steps.validate-files.outputs.has_files_changed }}
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Get changed files
      id: changed-files-root
      uses: tj-actions/changed-files@v29.0.1
      with:
        since_last_remote_commit: "true"

    - name: Validate changed files
      id: validate-files
      run: |
        for file in ${{ steps.changed-files-root.outputs.all_changed_and_modified_files }}; do
          if [[ $file == packages/bot/* ]] || [[ $file == .github/* ]]; then
            echo "Detected change in $file"
            echo ::set-output name=has_files_changed::1
            break
          fi
        done

  bot-build:
    needs: bot-setup
    if: needs.bot-setup.outputs.has_files_changed == 1
    runs-on: ubuntu-latest
    defaults:
       run:
         working-directory: ./packages/bot/
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'yarn'
        cache-dependency-path: ./packages/bot/yarn.lock
    - run: yarn install
    - run: yarn build
    - run: yarn test

  ##########
  # Scrape #
  ##########

  scrape-setup:
    runs-on: ubuntu-latest
    defaults:
       run:
         working-directory: ./packages/scrape/
    outputs:
      has_files_changed: ${{ steps.validate-files.outputs.has_files_changed }}
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Get changed files
      id: changed-files-root
      uses: tj-actions/changed-files@v29.0.1
      with:
        since_last_remote_commit: "true"

    - name: Validate changed files
      id: validate-files
      run: |
        for file in ${{ steps.changed-files-root.outputs.all_changed_and_modified_files }}; do
          if [[ $file == packages/scrape/* ]] || [[ $file == .github/* ]]; then
            echo "Detected change in $file"
            echo ::set-output name=has_files_changed::1
            break
          fi
        done

  scrape-build:
    needs: scrape-setup
    if: needs.scrape-setup.outputs.has_files_changed == 1
    runs-on: ubuntu-latest
    defaults:
       run:
         working-directory: ./packages/scrape/
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'yarn'
        cache-dependency-path: ./packages/scrape/yarn.lock
    - run: yarn install
    - run: yarn build
    - run: yarn test

  ########
  # Sync #
  ########

  sync-setup:
    runs-on: ubuntu-latest
    defaults:
       run:
         working-directory: ./packages/sync/
    outputs:
      has_files_changed: ${{ steps.validate-files.outputs.has_files_changed }}
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Get changed files
      id: changed-files-root
      uses: tj-actions/changed-files@v29.0.1
      with:
        since_last_remote_commit: "true"

    - name: Validate changed files
      id: validate-files
      run: |
        for file in ${{ steps.changed-files-root.outputs.all_changed_and_modified_files }}; do
          if [[ $file == packages/sync/* ]] || [[ $file == .github/* ]]; then
            echo "Detected change in $file"
            echo ::set-output name=has_files_changed::1
            break
          fi
        done

  sync-build:
    needs: sync-setup
    if: needs.sync-setup.outputs.has_files_changed == 1
    runs-on: ubuntu-latest
    defaults:
       run:
         working-directory: ./packages/sync/
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'yarn'
        cache-dependency-path: ./packages/sync/yarn.lock
    - run: yarn install
    - run: yarn build
    - run: yarn test