name: Deploy API

on: [workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
       run:
         working-directory: ./packages/api/
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'yarn'
        cache-dependency-path: ./packages/api/yarn.lock
    - run: yarn install
    - run: yarn build
    - run: echo "TODO - actually deploy"