name: Deploy API

on: [workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
       run:
         working-directory: ./packages/api/
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'yarn'
        cache-dependency-path: ./packages/api/yarn.lock
    - run: yarn install
    - run: yarn build
    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh/
        echo "$REMOTE_API_KEY" > ~/.ssh/api.key
        chmod 600 ~/.ssh/api.key
        cat >>~/.ssh/config <<END
        Host api
          HostName $REMOTE_API_HOST
          User $REMOTE_API_USER
          IdentityFile ~/.ssh/api.key
          StrictHostKeyChecking no
        END
      env:
        REMOTE_API_USER: ${{ secrets.REMOTE_API_USER }}
        REMOTE_API_KEY: ${{ secrets.REMOTE_API_KEY }}
        REMOTE_API_HOST: ${{ secrets.REMOTE_API_HOST }}
    - name: rsync build
      run:  rsync -aP dist/* api:${{ secrets.REMOTE_API_PATH }}
    - name: Restart service
      run: ssh api 'ls ${{ secrets.REMOTE_API_PATH }}'